#!/usr/bin/env bash

usage="$(basename $0) [editor] [path.md]"

if [[ ${1: -3} == ".md" ]]; then
	filename=$1
	editor="$2"
else
	filename=~/Writing/Now/$(date +"%G%m%d").md
	editor="$1"
fi
if [[ ! -a $filename ]]; then
	touch $filename
fi
if [ -n "$editor" ]; then
	$editor $filename
else
	open $filename -a /Applications/iA\ Writer.app
fi
