#!/usr/bin/env bash

usage="to-jpg <files>"

if [[ -z $* ]]; then
	echo "$usage"
	exit 1
fi

outdir=$(pwd)
quality="90"

for f in "$@"; do
	base=$(basename "$f")
	filename=${base%.*}
	mogrify -format jpg -quality $quality "$f"
done

