#!/usr/bin/env bash

width=320
fps=25
palette=false

usage="video-to-gif [width=$width] [fps=$fps] [palette=$palette] [out=filepath] video"

# Parse arguments
while true; do
	if ! [[ "$1" == *"="* ]]; then
		break
	fi
	var="$1"
	val="$(sed 's/.*=//' <<< "$var")"
	key="$(sed 's/=.*//' <<< "$var")"
	shift
	case $key in
		palette )
			palette=true
			;;
		width )
			width=$val
			;;
		fps )
			fps=$val
			;;
		out )
			outfile=$val
			;;
		* )
			echo "option $key not valid"
			echo $usage
			exit 2
			;;
	esac
done

if [[ -z "$1" ]]; then
	echo "requires video input"
	echo "usage: $usage"
	exit 1
fi

input="$@"

# Extract filename segments
base=$(basename $1)
extension="${base##*.}"
filename="${base%.*}"
if [[ -z "$outfile" ]]; then
	outfile="$filename.gif"
fi

# Scaling & FPS
filter="fps=$fps,scale=$width:-1"


if [[ $palette == true ]]; then
	# Generate palette
	ffmpeg -y -i $input -vf "$filter:flags=lanczos,palettegen" palette.png

	# Generate gif using palette
	ffmpeg -y -i $input -i palette.png -filter_complex "$filter:flags=lanczos[x];[x][1:v]paletteuse" $outfile
else
	# No palette creates smaller files
	ffmpeg -y -i $input -vf "$filter" $outfile
fi
